### PR TITLE
fix unique email, NRIC or phone number 

### LINKED ISSUE #53: Check  NRIC, phone number or email for duplicates instead of Name
As a police officer, I want to have no repeated data so that I can avoid duplicate entries. (check by  NRIC , email or phone number)

### LINKED ISSUE #67: Fix JsonSerializableAddressBookTest.java failed test case
_Originally posted by @Impala36 in https://github.com/AY2021S2-TIC4002-F18-1/tp2/pull/65#discussion_r589486234_

### PR DESCRIPTION
**Pull request by linqing42**

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -91,7 +91,10 @@ public boolean isSamePerson(Person otherPerson) {
         }
 
         return otherPerson != null
-            && (otherPerson.getNric().equals(getNric()) || otherPerson.getPhone().equals(getPhone()));
+                && otherPerson.getName().equals(getName())
+                && otherPerson.getNric().equals(getNric())
+                && otherPerson.getPhone().equals(getPhone())
+                && otherPerson.getEmail().equals(getEmail());
```
Comment (Impala36) [inline src/main/java/seedu/address/model/person/Person.java:102]: There might be an issue with this.
Previously it was getName AND (getNric OR getPhone).
Now it is getName AND getNric AND getPhone AND getEmail.

**Review by Impala36 — APPROVED** [review]
1 failed test case reported, will look into it soon.

File: src/main/java/seedu/address/model/person/Person.java (hunk 1 above)
Comment (linqing42) [reply src/main/java/seedu/address/model/person/Person.java:102]: noted
